name: Illustrate
version: '${project.version}'
main: me.santio.illustrate.Illustrate
api-version: 1.17
authors: [ Santio71 ]
description: Painting in minecraft
commands:
  togglepaint:
    description: Toggle painting in a single/all world(s)
    permission: illustrate.togglepaint
    aliases: [togglepainting]